services:
  - type: web
    name: tg-suggest-bot
    env: python
    startCommand: python bot.py
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: 8528634273:AAEKpl5KWTMuKNOrOgAAhuSYE9-zyhYXxp0
      - key: ADMIN_IDS
        value: 955483416,2025057922
      - key: CHANNEL_ID
        value: -1002933285938
      - key: WEBHOOK_URL
        value: https://tg-suggest-bot.onrender.com/webhook
